/*
 * This file is generated by jOOQ.
 */
package fido.capstone.webauthn.db;

import javax.annotation.Generated;

import fido.capstone.webauthn.db.tables.AppUser;
import fido.capstone.webauthn.db.tables.Credentials;

/**
 * Convenience access to all tables in webauthn
 */
@Generated(value = { "http://www.jooq.org", "jOOQ version:3.11.11" },
    comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

  /**
   * The table <code>webauthn.app_user</code>.
   */
  public static final AppUser APP_USER = fido.capstone.webauthn.db.tables.AppUser.APP_USER;

  /**
   * The table <code>webauthn.credentials</code>.
   */
  public static final Credentials CREDENTIALS = fido.capstone.webauthn.db.tables.Credentials.CREDENTIALS;
}
