/*
 * This file is generated by jOOQ.
 */
package ch.rasc.webauthn.db.tables.records;

import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;

import ch.rasc.webauthn.db.tables.AppUser;

/**
 * This class is generated by jOOQ.
 */
@Generated(value = { "http://www.jooq.org", "jOOQ version:3.11.11" },
    comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AppUserRecord extends UpdatableRecordImpl<AppUserRecord>
    implements Record8<Long, String, String, String, byte[], LocalDateTime, LocalDateTime, byte[]> {

  private static final long serialVersionUID = 1353066315;

  /**
   * Setter for <code>webauthn.app_user.id</code>.
   */
  public void setId(Long value) {
    set(0, value);
  }

  /**
   * Getter for <code>webauthn.app_user.id</code>.
   */
  public Long getId() {
    return (Long) get(0);
  }

  /**
   * Setter for <code>webauthn.app_user.username</code>.
   */
  public void setUsername(String value) {
    set(1, value);
  }

  /**
   * Getter for <code>webauthn.app_user.username</code>.
   */
  public String getUsername() {
    return (String) get(1);
  }
  
  
  


  public void setName(String value) {
	set(2, value);
  }

	  
  public String getName() {
	 return (String) get(2);
}
  
  
  public void setEmail(String value) {
	set(3, value);
  }

	  
  public String getEmail() {
	 return (String) get(3);
}
  
  
  

  /**
   * Setter for <code>webauthn.app_user.recovery_token</code>.
   */
  public void setRecoveryToken(byte... value) {
    set(4, value);
  }

  /**
   * Getter for <code>webauthn.app_user.recovery_token</code>.
   */
  public byte[] getRecoveryToken() {
    return (byte[]) get(4);
  }

  /**
   * Setter for <code>webauthn.app_user.registration_start</code>.
   */
  public void setRegistrationStart(LocalDateTime value) {
    set(5, value);
  }

  /**
   * Getter for <code>webauthn.app_user.registration_start</code>.
   */
  public LocalDateTime getRegistrationStart() {
    return (LocalDateTime) get(5);
  }

  /**
   * Setter for <code>webauthn.app_user.registration_add_start</code>.
   */
  public void setRegistrationAddStart(LocalDateTime value) {
    set(6, value);
  }

  /**
   * Getter for <code>webauthn.app_user.registration_add_start</code>.
   */
  public LocalDateTime getRegistrationAddStart() {
    return (LocalDateTime) get(6);
  }

  /**
   * Setter for <code>webauthn.app_user.registration_add_token</code>.
   */
  public void setRegistrationAddToken(byte... value) {
    set(7, value);
  }

  /**
   * Getter for <code>webauthn.app_user.registration_add_token</code>.
   */
  public byte[] getRegistrationAddToken() {
    return (byte[]) get(7);
  }

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------

  /**
   * {@inheritDoc}
   */
  @Override
  public Record1<Long> key() {
    return (Record1) super.key();
  }

  // -------------------------------------------------------------------------
  // Record6 type implementation
  // -------------------------------------------------------------------------

  /**
   * {@inheritDoc}
   */
  @Override
  public Row8<Long, String, String, String, byte[], LocalDateTime, LocalDateTime, byte[]> fieldsRow() {
    return (Row8) super.fieldsRow();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Row8<Long, String,String, String, byte[], LocalDateTime, LocalDateTime, byte[]> valuesRow() {
    return (Row8) super.valuesRow();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Field<Long> field1() {
    return AppUser.APP_USER.ID;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Field<String> field2() {
    return AppUser.APP_USER.USERNAME;
  }
  
  
  /**
   * {@inheritDoc}
   */
  @Override
  public Field<String> field3() {
    return AppUser.APP_USER.NAME;
  }
  
  
  /**
   * {@inheritDoc}
   */
  @Override
  public Field<String> field4() {
    return AppUser.APP_USER.EMAIL;
  }
  
  

  /**
   * {@inheritDoc}
   */
  @Override
  public Field<byte[]> field5() {
    return AppUser.APP_USER.RECOVERY_TOKEN;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Field<LocalDateTime> field6() {
    return AppUser.APP_USER.REGISTRATION_START;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Field<LocalDateTime> field7() {
    return AppUser.APP_USER.REGISTRATION_ADD_START;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Field<byte[]> field8() {
    return AppUser.APP_USER.REGISTRATION_ADD_TOKEN;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Long component1() {
    return getId();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public String component2() {
    return getUsername();
  }
  
  

  /**
   * {@inheritDoc}
   */
  @Override
  public String component3() {
    return getName();
  }
  
  

  /**
   * {@inheritDoc}
   */
  @Override
  public String component4() {
    return getEmail();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public byte[] component5() {
    return getRecoveryToken();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public LocalDateTime component6() {
    return getRegistrationStart();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public LocalDateTime component7() {
    return getRegistrationAddStart();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public byte[] component8() {
    return getRegistrationAddToken();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Long value1() {
    return getId();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public String value2() {
    return getUsername();
  }
  
  @Override
  public String value3() {
	    return getName();
	  }
  @Override
  public String value4() {
	    return getEmail();
	  }

  /**
   * {@inheritDoc}
   */
  @Override
  public byte[] value5() {
    return getRecoveryToken();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public LocalDateTime value6() {
    return getRegistrationStart();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public LocalDateTime value7() {
    return getRegistrationAddStart();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public byte[] value8() {
    return getRegistrationAddToken();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public AppUserRecord value1(Long value) {
    setId(value);
    return this;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public AppUserRecord value2(String value) {
    setUsername(value);
    return this;
  }
  
  @Override
  public AppUserRecord value3(String value) {
	    setName(value);
	    return this;
  }
  @Override
  public AppUserRecord value4(String value) {
	    setEmail(value);
	    return this;
}

  /**
   * {@inheritDoc}
   */
  @Override
  public AppUserRecord value5(byte... value) {
    setRecoveryToken(value);
    return this;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public AppUserRecord value6(LocalDateTime value) {
    setRegistrationStart(value);
    return this;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public AppUserRecord value7(LocalDateTime value) {
    setRegistrationAddStart(value);
    return this;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public AppUserRecord value8(byte... value) {
    setRegistrationAddToken(value);
    return this;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public AppUserRecord values(Long value1, String value2, String value3, String value4, byte[] value5,
      LocalDateTime value6, LocalDateTime value7, byte[] value8) {
    value1(value1);
    value2(value2);
    value3(value3);
    value4(value4);
    value5(value5);
    value6(value6);
    value7(value7);
    value8(value8);
    return this;
  }

  // -------------------------------------------------------------------------
  // Constructors
  // -------------------------------------------------------------------------

  /**
   * Create a detached AppUserRecord
   */
  public AppUserRecord() {
    super(AppUser.APP_USER);
  }

  /**
   * Create a detached, initialised AppUserRecord
   */
  public AppUserRecord(Long id, String username, String name, String email, byte[] recoveryToken,
      LocalDateTime registrationStart, LocalDateTime registrationAddStart,
      byte[] registrationAddToken) {
    super(AppUser.APP_USER);

    set(0, id);
    set(1, username);
    set(2, name);
    set(3, email);
    set(4, recoveryToken);
    set(5, registrationStart);
    set(6, registrationAddStart);
    set(7, registrationAddToken);
  }
}
